# Document:
# http://simiki.org/docs/configuration.html

url: https://en.worldsecrets.net
title: Full Record of the World's Unsolved Mysteries
keywords: Unsolved mysteries, Supernatural power, Occult
description: This site aims to include cases of unsolved mysteries around the world,include
author: A-Middle-School-Student

root: /
source: content
destination: output
themes_dir: themes
theme: simple2

category:
  - name: linux  # 目录名
    label: Linux/运维  # 目录的别名, 生成首页时可以使用
  - name: database
    label: 数据库

default_ext: md
pygments: false
debug: false